on:
  push:
    branches:
      - main
      - master

name: build-site

jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Install tidyverse
        run: Rscript -e 'install.packages(c("dplyr", "readr", "ggplot2"))'


      - name: install stringi R
        run: Rscript -e 'install.packages("stringi")'

      - name: download stringi ubuntu
        run: wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3.2_amd64.deb 

      - name: install stringi ubuntu
        run: sudo apt-get install ./libicu60_60.2-3ubuntu3.2_amd64.deb

      - name: Build website
        run: |
          Rscript -e 'rmarkdown::render_site()'
          touch _site/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
